/*!CK:243753395!*//*1452732651,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["gZyZF"]); }

__d('GamesTab',['CSS','cx'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();function j(k,l){'use strict';this.$GamesTab1=l.category;this.$GamesTab2=l.nub;this.$GamesTab3=k;}j.prototype.getCategory=function(){'use strict';return this.$GamesTab1;};j.prototype.getRoot=function(){'use strict';return this.$GamesTab3;};j.prototype.select=function(){'use strict';h.addClass(this.$GamesTab3,"_1yiw");h.show(this.$GamesTab2);};j.prototype.unselect=function(){'use strict';h.removeClass(this.$GamesTab3,"_1yiw");h.hide(this.$GamesTab2);};f.exports=j;},null);
__d("GamesTabContentUpdateManager",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h=null,i={register:function(j){h=j;},setTabContent:function(j,k){if(h)h.setTabContent(j,k);}};f.exports=i;},null);
__d('GamesTabMenu',['AsyncRequest','XPlatformXOutableElementController'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();function j(k,l){'use strict';this.$GamesTabMenu1=l.xoutType;this.$GamesTabMenu2=l.fbid;k.subscribe('itemclick',(function(m,n){switch(n.item.getValue()){case 'xout':this.$GamesTabMenu3();break;}}).bind(this));}j.prototype.setContainer=function(k){'use strict';this.$GamesTabMenu4=k;};j.prototype.$GamesTabMenu3=function(){'use strict';if(this.$GamesTabMenu4){this.$GamesTabMenu4.getRoot().remove();var k=i.getURIBuilder().setEnum('type',this.$GamesTabMenu1).setInt('fbid',this.$GamesTabMenu2).getURI();new h(k).setMethod('POST').send();}};f.exports=j;},null);
__d('GamesTabPanel',['CSS','getStyleProperty'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();function j(k,l){'use strict';this.$GamesTabPanel1=k;}j.prototype.showPanel=function(){'use strict';h.show(this.$GamesTabPanel1);};j.prototype.hidePanel=function(){'use strict';h.hide(this.$GamesTabPanel1);};j.prototype.getHeight=function(){'use strict';return i(this.$GamesTabPanel1,'height');};f.exports=j;},null);
__d("XGamesTabUnitAsyncController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/games\/tabs\/content\/",{panel_type:{type:"Enum",required:true,enumType:0},tab_category:{type:"Enum",required:true,enumType:0},fbsource:{type:"Int",required:true}});},null);
__d('GamesTabUnit',['Arbiter','AsyncRequest','CSS','Event','GamesTabContentUpdateManager','XGamesTabUnitAsyncController','tidyEvent'],function a(b,c,d,e,f,g,h,i,j,k,l,m,n){if(c.__markCompiled)c.__markCompiled();function o(p,q){'use strict';this.$GamesTabUnit1=p;this.$GamesTabUnit2=q.fbsource;this.$GamesTabUnit3=q.initialCategory;this.$GamesTabUnit4=q.loadingBar;this.$GamesTabUnit5=q.panelType;this.$GamesTabUnit6=q.tabIcons;this.$GamesTabUnit7=q.tabPanels;this.$GamesTabUnit8=q.arbiterEvent;this.$GamesTabUnit9=q.tabMenu;this.$GamesTabUnit10=this.$GamesTabUnit3;this.$GamesTabUnit11={};this.$GamesTabUnit11[this.$GamesTabUnit3]=true;this.$GamesTabUnit12=this.$GamesTabUnit7[this.$GamesTabUnit3].getHeight();l.register(this);if(this.$GamesTabUnit9)this.$GamesTabUnit9.setContainer(this);Object.keys(this.$GamesTabUnit6).forEach((function(r){return this.$GamesTabUnit13(this.$GamesTabUnit6[r]);}).bind(this));}o.prototype.getRoot=function(){'use strict';return this.$GamesTabUnit1;};o.prototype.setTabContent=function(p,q){'use strict';this.$GamesTabUnit7[q]=p;if(q===this.$GamesTabUnit10){j.hide(this.$GamesTabUnit4);this.$GamesTabUnit7[q].showPanel();this.$GamesTabUnit12=this.$GamesTabUnit7[q].getHeight();}};o.prototype.$GamesTabUnit13=function(p){'use strict';var q=p.getCategory();n(k.listen(p.getRoot(),'click',(function(){if(q===this.$GamesTabUnit10)return;this.$GamesTabUnit6[this.$GamesTabUnit10].unselect();if(this.$GamesTabUnit7[this.$GamesTabUnit10]){this.$GamesTabUnit12=this.$GamesTabUnit7[this.$GamesTabUnit10].getHeight();this.$GamesTabUnit7[this.$GamesTabUnit10].hidePanel();}this.$GamesTabUnit6[q].select();this.$GamesTabUnit10=q;if(this.$GamesTabUnit7[q]){j.hide(this.$GamesTabUnit4);this.$GamesTabUnit7[q].showPanel();this.$GamesTabUnit12=this.$GamesTabUnit7[q].getHeight();if(q===this.$GamesTabUnit3&&this.$GamesTabUnit8){h.inform(this.$GamesTabUnit8);this.$GamesTabUnit8=null;}return;}this.$GamesTabUnit4.style.height=this.$GamesTabUnit12;j.show(this.$GamesTabUnit4);if(this.$GamesTabUnit11[q])return;this.$GamesTabUnit11[q]=true;var r=m.getURIBuilder().setEnum('panel_type',this.$GamesTabUnit5).setEnum('tab_category',q).setInt('fbsource',this.$GamesTabUnit2).getURI();new i().setURI(r).send();}).bind(this)));};f.exports=o;},null);